### PR TITLE
Add RecursiveSerializer

### PR DESCRIPTION
**Pull request by Andrew-Dickinson**
Adds a `RecursiveSerializer` class, which enables child serializers to provide recursive model serialization

Uses automatic permissions detection to determine if the user is authorized to access the foreign model, restricting the fields available to just the primary key if not

### CODE REVIEW

**Comment by Andrew-Dickinson** [comment]
Some examples of the new serialized outputs:

Install (with full permissions):
```json
{
    "install_number": 2,
    "member": {
        "id": 1,
        "name": "redacted",
        "email_address": "redacted",
        "stripe_email_address": null,
        "secondary_emails": [
            "redacted"
        ],
        "phone_number": null,
        "slack_handle": null,
        "invalid": false,
        "contact_notes": null
    },
    "building": {
        "id": 1,
        "bin": null,
        "building_status": "Inactive",
        "street_address": "redacted",
        "city": "redacted",
        "state": "NY",
        "zip_code": "redacted",
        "invalid": true,
        "address_truth_sources": "PeliasStringParsing",
        "latitude": 0,
        "longitude": 0,
        "altitude": 37.0,
        "primary_nn": 2,
        "node_name": null,
        "notes": ""
    },
    "network_number": 2,
    "install_status": "Inactive",
    "ticket_id": null,
    "request_date": "redacted",
    "install_date": "redacted",
    "abandon_date": null,
    "unit": "4J",
    "roof_access": false,
    "referral": null,
    "notes": ""
}
```


Install (with no member/building permissions):
```json
{
    "install_number": 2,
    "member": {
        "id": 1
    },
    "building": {
        "id": 1
    },
    "network_number": 2,
    "install_status": "Inactive",
    "ticket_id": null,
    "request_date": "redacted",
    "install_date": "redacted",
    "abandon_date": null,
    "unit": "redacted",
    "roof_access": false,
    "referral": null,
    "notes": ""
}
```

Building (with full permissions):
```json
{
    "id": 2,
    "installs": [
        {
            "install_number": 3,
            "member": {
                "id": 2,
                "name": "Brian Hall",
                "email_address": "redacted",
                "stripe_email_address": null,
                "secondary_emails": [],
                "phone_number": "redacted",
                "slack_handle": null,
                "invalid": false,
                "contact_notes": null
            },
            "network_number": 3,
            "install_status": "Active",
            "ticket_id": null,
            "request_date": "redacted",
            "install_date": "redacted",
            "abandon_date": null,
            "unit": "redacted",
            "roof_access": false,
            "referral": null,
            "notes": ""
        }
    ],
    "bin": null,
    "building_status": "Active",
    "street_address": "redacted",
    "city": "New York",
    "state": "NY",
    "zip_code": "redacted",
    "invalid": true,
    "address_truth_sources": "PeliasStringParsing",
    "latitude": 0,
    "longitude": 0,
    "altitude": 27.0,
    "primary_nn": 3,
    "node_name": "Brian",
    "notes": ""
}
```

**Comment by Andrew-Dickinson** [comment]
TODO: The webhooks still follow the old syntax. This actually might be an annoying problem to solve since our upstream webhooks library doesn't support DRF serializers. Don't hate me 🫣 if I want to switch to this one: https://github.com/am-flow/drf-hooks

**Comment by Andrew-Dickinson** [comment]
Removed failing tests for webhooks, these are included in #155, which overhauls the webhook system to allow recursive serialization

**Review by WillNilges — APPROVED** [review]
🚢

**Pull request merged**
