### PR TITLE
Add DIY field

### PR DESCRIPTION
**Pull request by Andrew-Dickinson**
Adds a DIY field to the install model. This is populated based on the text "diy" appearing anywhere in the imported notes, and is set to `null` for installs that never got installed

### CODE REVIEW

**Comment by Andrew-Dickinson** [comment]
Closes #73

**Review by WillNilges — APPROVED** [review]
Love it. Is this something we want to expose to the Member on the Join Form, or should we leave it up to Olivier on the Join Form?

One Nit: Please make sure that the checkbox shows up in a reasonable place on the Admin Panel, and if it does not, at least make an issue for it!!!

**Comment by Andrew-Dickinson** [comment]
Oh good call. Because we're using a custom admin form, it's actually not present by default. I will add it

**Comment by Andrew-Dickinson** [comment]
My thought was yeah that this ends up being admin-maintained metadata. DIYs are rare so that should be no problem

**Pull request merged**
